version: '3.3'

services:
  janus:
    image: tokend/janus:latest
    restart: unless-stopped
    volumes:
      - ./configs/janus.toml:/etc/janus/janus.toml
  upstream:
    image: nginx
    restart: unless-stopped
    volumes:
    - ./configs/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "8000:80"
  adks:
    image: tokend/adks:1.0.0
    restart: unless-stopped
    depends_on:
      - horizon
      - adks_db
    ports:
      - 8006:80
    volumes:
      - ./configs/adks.toml:/config.toml
  adks_db:
    image: tokend/postgres-ubuntu:9.6
    restart: unless-stopped
    environment:
      - POSTGRES_USER=adks
      - POSTGRES_PASSWORD=adks
      - POSTGRES_DB=adks
      - PGDATA=/pgdata
    volumes:
      - adks-data:/pgdata
  core:
    image: tokend/core:3.5.1
    depends_on:
      - janus
    restart: unless-stopped
    environment:
      - POSTGRES_USER=core
      - POSTGRES_PASSWORD=core
      - POSTGRES_DB=core
      - PGDATA=/data/pgdata
      - ENSUREDB=1
      - CONFIG=/core-config.ini
    volumes:
      - ./configs/core.ini:/core-config.ini
      - core-data:/data
    labels:
      - "autoheal=true"
  horizon:
    image: tokend/horizon:3.5.1-x.3
    depends_on:
      - core
    restart: unless-stopped
    environment:
      - POSTGRES_USER=horizon
      - POSTGRES_PASSWORD=horizon
      - POSTGRES_DB=horizon
      - PGDATA=/data/pgdata
    volumes:
      - ./configs/horizon.yaml:/config.yaml
      - horizon-data:/data
  api:
    image: tokend/identity:4.5.1-phone.2
    restart: unless-stopped
    depends_on:
      - horizon
      - api_db
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/api.yml:/config.yaml
    command: run
  api_db:
    image: tokend/postgres-ubuntu:9.6
    restart: unless-stopped
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=api
      - POSTGRES_DB=api
      - PGDATA=/pgdata
    volumes:
      - api-data:/pgdata
  initscripts:
    image: tokend/terraform-provider-tokend:1.2.0
    depends_on:
      - horizon
      - storage
    restart: on-failure
    volumes:
      - ./terraform:/opt/config
    entrypoint: ""
    command: /opt/config/apply.sh
  web_client:
    image: tokend/web-client:1.10.0-rc.1
    restart: unless-stopped
    volumes:
      - ./configs/client.js:/usr/share/nginx/html/static/env.js
    ports:
      - 8060:80
  conto_client:
    image: tokendconto/web-client:1.0.0-rc.7
    restart: unless-stopped
    volumes:
      - ./configs/conto.js:/usr/share/nginx/html/static/env.js
    ports:
      - 8050:80
  admin_client:
    image: tokend/admin-client:1.10.0-rc.2
    restart: unless-stopped
    volumes:
      - ./configs/client.js:/usr/share/nginx/html/static/env.js
    ports:
      - 8070:80
  storage:
    image: minio/minio:RELEASE.2019-01-31T00-31-19Z
    restart: unless-stopped
    entrypoint: "sh"
    command: -c "mkdir -p /data/tfstate && minio server /data"
    environment:
      - MINIO_ACCESS_KEY=miniominio
      - MINIO_SECRET_KEY=sekritsekrit
      - MINIO_BROWSER=off
    volumes:
      - storage-data:/data
  dns:
    image: tokend/dns:0.2.9
    restart: unless-stopped
    environment:
      - KV_VIPER_FILE=/config.yaml
    depends_on:
      - horizon
      - dns_db
    volumes:
      - ./configs/dns.yaml:/config.yaml
    entrypoint: sh -c "dns-svc migrate up && dns-svc run"
  dns_db:
    image: tokend/postgres-ubuntu:9.6
    restart: unless-stopped
    environment:
      - POSTGRES_USER=dns
      - POSTGRES_PASSWORD=dns
      - POSTGRES_DB=dns
      - PGDATA=/pgdata
    volumes:
      - dns-data:/pgdata

  ##
  ## Auxiliary modules
  ##

  charts:
    image: tokend/charts:0.4.1
    restart: unless-stopped
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/charts.yaml:/config.yaml
    ports:
      - 8080:8080
    command: run
  salecloser:
    image: tokend/sale-closer-svc:1.0.1
    depends_on:
      - horizon
    restart: unless-stopped
    volumes:
      - ./configs/salecloser.yaml:/config.yaml
    environment:
      - KV_VIPER_FILE=/config.yaml
    command: "run"
  poll_closer:
    image: tokend/poll-closer:0.1.1
    restart: unless-stopped
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/poll-closer.yaml:/config.yaml
    command: run closer

  ## 3rd party

  autoheal:
    image: willfarrell/autoheal
    restart: unless-stopped
    environment:
      - AUTOHEAL_START_PERIOD=60
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ##
  ## Integration services
  ##

  ## Coinpayments

  coinpayments-deposit:
    image: tokend/coinpayments:0.4.0
    restart: unless-stopped
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/coinpayments-deposit.yaml:/config.yaml
    command: deposit
  coinpayments-deposit-verify:
    image: tokend/coinpayments:0.4.0
    restart: unless-stopped
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/coinpayments-deposit-verify.yaml:/config.yaml
    command: deposit-verify
  coinpayments-withdraw:
    image: tokend/coinpayments:0.4.0
    restart: unless-stopped
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/coinpayments-withdraw.yaml:/config.yaml
    command: withdraw
  coinpayments-atomic-swap-checker:
    image: tokend/coinpayments:0.4.3-x.4
    restart: unless-stopped
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/coinpayments-atomic-swap-checker.yaml:/config.yaml
    command: atomic-swap-checker
  coinpayments-atomic-swap-matcher:
    image: tokend/coinpayments:0.4.3-x.4
    restart: unless-stopped
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/coinpayments-atomic-swap-matcher.yaml:/config.yaml
    command: atomic-swap-matcher
  notificator:
    image: registry.gitlab.com/distributed_lab/notificator-server:e603cc413f0c1f3977addef0d4a9e213d11e8aea
    restart: unless-stopped
    depends_on:
      - horizon
      - notificator_db
    volumes:
      - ./configs/notificator.yaml:/config.yaml
    command:
      - "notificator"
      - "--config"
      - "/config.yaml"
      - "--migrations"
      - "/migrations"
      - "run"
  notificator_db:
    image: tokend/postgres-ubuntu:9.6
    restart: unless-stopped
    environment:
      - POSTGRES_USER=notificator
      - POSTGRES_PASSWORD=notificator
      - POSTGRES_DB=notificator
      - PGDATA=/pgdata
    volumes:
      - notificator-data:/pgdata
  templatesprovider:
    image: registry.gitlab.com/tokend/templates-svc:4603b974928fc90186973a9b103fb420e840f125
    restart: unless-stopped
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/templatesprovider.yaml:/config.yaml
    command:
      - 'run'
      - 'service'

volumes:
  adks-data:
  api-data:
  core-data:
  horizon-data:
  storage-data:
  dns-data:
  notificator-data:
