version: '3.3'

networks: 
  test:
    external:
      name: net_test 

services:
  traefik:
    image: traefik:v2.0
    ports:
      - "80:80"
      - "8081:8080"
    volumes:
      - ./configs/traefik.yaml:/traefik.yaml
    networks:
      - test

  cop:
    image: tokend/traefik-cop:1.0.0
    restart: unless-stopped
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/cop.yaml:/config.yaml
    entrypoint: sh -c "traefik-cop run"
    networks:
      - test

  upstream:
    image: nginx
    restart: unless-stopped
    volumes:
    - ./configs/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "8000:80"
    networks:
      - test

  identities:
    image: identities:latest # registry.gitlab.com/tokend/nbu/identity-svc:0b6bebf545e88c6c7deed0ef1592f1e797fd45ab
    restart: unless-stopped
    entrypoint: sh -c "identity-svc migrate up && identity-svc run service"
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/identities.yaml:/config.yaml
      - ./configs/sdkconf.yaml:/sdkconf.yaml
      - ./organizations:/organizations
    networks:
      - test

  identities_db:
    image: tokend/postgres-ubuntu:9.6
    restart: unless-stopped
    environment:
      - POSTGRES_USER=identities
      - POSTGRES_PASSWORD=identities
      - POSTGRES_DB=identities
      - PGDATA=/pgdata
    volumes:
      - identities-data:/pgdata
    networks:
      - test

  sallyport:
    image: sallyport:latest # registry.gitlab.com/tokend/nbu/sallyport-svc:b559a3764d83060f455dd9f5cbe52f1e761942fc
    environment:
      - KV_VIPER_FILE=/config.yaml
    command: run service
    volumes:
      - ./configs/sallyport.yaml:/config.yaml
    networks:
      - test

volumes:
  identities-data:
