version: '3.3'

services:
  upstream:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"
  api:
    image: registry.gitlab.com/tokend/api:dd88ff3846be023404c8372583ea451a7efa85e6
    restart: unless-stopped
    depends_on:
      - horizon
      - api_db
      - doorman
    environment:
      - KV_VIPER_FILE=/config.yaml
      - POSTGRES_USER=api
      - DBHOST=api_db
    volumes:
      - ./configs/api.yaml:/config.yaml
  api_db:
    image: tokend/postgres-ubuntu:9.6
    labels:
      - "traefik.enabled=false"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=api
      - POSTGRES_DB=api
      - PGDATA=/pgdata
    volumes:
      - api-data:/pgdata
  doorman:
    image: registry.gitlab.com/tokend/accounts-ingester-svc:84442c75ad72fc6e954bec70c37eb49db173c67b
    restart: unless-stopped
    depends_on:
      - horizon
      - doorman_db
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/doorman.yaml:/config.yaml
    entrypoint: sh -c "accounts-ingester-svc migrate up && accounts-ingester-svc run"
  doorman_db:
    image: tokend/postgres-ubuntu:9.6
    restart: unless-stopped
    environment:
      - POSTGRES_USER=doorman
      - POSTGRES_PASSWORD=doorman
      - POSTGRES_DB=doorman
      - PGDATA=/pgdata
    volumes:
      - doorman-data:/pgdata
    labels:
      - "traefik.enabled=false"
  traefik:
    image: traefik:v2.0
    ports:
      - "80:80"
      - "8001:80"
      - "8080:8080"
    volumes:
      - ./configs/traefik.yaml:/traefik.yaml
  cop:
    image: registry.gitlab.com/tokend/traefik-cop:fec7ae95c2395f99c6e570612e6220bf368da016
    restart: unless-stopped
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/cop.yaml:/config.yaml
    entrypoint: sh -c "traefik-cop run"
    depends_on:
      - traefik
  redis:
    image: redis:5.0-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
    command:
      - redis-server
      - --appendonly
      - "yes"
  core:
    image: registry.gitlab.com/tokend/go-core:4c90ba0481e14adbff0e9565c5b6a03dbc9bc5bc
    depends_on:
      - core_db
      - cop
    restart: unless-stopped
    environment:
      - POSTGRES_USER=core
      - DBHOST=core_db
      - KV_VIPER_FILE=config.yaml
    volumes:
      - ./configs/core.yaml:/config.yaml
    labels:
      - "autoheal=true"
  horizon:
    image: registry.gitlab.com/tokend/ingester:9fb7cfdf06543b53e58e31d9076052be6c17b9d4
    depends_on:
      - core
      - horizon_db
    restart: unless-stopped
    environment:
      - INGESTER_POSTGRES_USER=horizon
      - CORE_POSTGRES_USER=core
      - INGESTER_DBHOST=horizon_db
      - CORE_DBHOST=core_db
      - KV_VIPER_FILE=config.yaml
    volumes:
      - ./configs/horizon.yaml:/config.yaml
      - horizon-data:/data
  core_db:
    image: tokend/postgres-ubuntu:9.6
    restart: unless-stopped
    environment:
      - POSTGRES_USER=core
      - POSTGRES_PASSWORD=core
      - POSTGRES_DB=core
      - PGDATA=/pgdata
    volumes:
      - core-data:/pgdata
    labels:
      - "traefik.enabled=false"
  horizon_db:
    image: tokend/postgres-ubuntu:9.6
    restart: unless-stopped
    environment:
      - POSTGRES_USER=horizon
      - POSTGRES_PASSWORD=horizon
      - POSTGRES_DB=horizon
      - PGDATA=/pgdata
    volumes:
      - horizon-data:/pgdata
    labels:
      - "traefik.enabled=false"
  initscripts:
    image: khramov/terraform-provider-tokend:0.0.8
    depends_on:
      - horizon
      - storage
    restart: on-failure
    volumes:
      - ./terraform:/opt/config
    entrypoint: ""
    command: /opt/config/apply.sh
  storage:
    image: minio/minio:RELEASE.2019-01-31T00-31-19Z
    restart: unless-stopped
    entrypoint: "sh"
    command: -c "mkdir -p /data/tfstate && minio server /data"
    environment:
      - MINIO_ACCESS_KEY=miniominio
      - MINIO_SECRET_KEY=sekritsekrit
      - MINIO_BROWSER=off
    volumes:
      - storage-data:/data

  #Conto related
  marketplace:
    image: registry.gitlab.com/tokend/marketplace-svc:58e6808523286d10f7a36681401cd2a90982269a
    restart: unless-stopped
    environment:
      - KV_VIPER_FILE=/config.yaml
    depends_on:
      - horizon
      - marketplace_db
    volumes:
      - ./configs/marketplace.yaml:/config.yaml
    entrypoint: sh -c "marketplace-svc migrate up && marketplace-svc run"
  marketplace_db:
    image: tokend/postgres-ubuntu:9.6
    restart: unless-stopped
    environment:
      - POSTGRES_USER=marketplace
      - POSTGRES_PASSWORD=marketplace
      - POSTGRES_DB=marketplace
      - PGDATA=/pgdata
    volumes:
      - marketplace-data:/pgdata

  dns:
    image: registry.gitlab.com/tokend/dns-svc:2fdd8a17d8ca88d7cefcf438324950378858fa31
    restart: unless-stopped
    environment:
      - KV_VIPER_FILE=/config.yaml
    depends_on:
      - api
      - dns_db
    volumes:
      - ./configs/dns.yaml:/config.yaml
    entrypoint: sh -c "dns-svc migrate up && dns-svc run"
  dns_db:
    image: tokend/postgres-ubuntu:9.6
    restart: unless-stopped
    environment:
      - POSTGRES_USER=dns
      - POSTGRES_PASSWORD=dns
      - POSTGRES_DB=dns
      - PGDATA=/pgdata
    volumes:
      - dns-data:/pgdata

  ## 3rd party

  autoheal:
    image: willfarrell/autoheal
    restart: unless-stopped
    environment:
      - AUTOHEAL_START_PERIOD=60
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  adks-data:
  api-data:
  core-data:
  horizon-data:
  storage-data:
  redis-data:
  doorman-data:
  marketplace-data:
  dns-data:

