version: '3.3'

services:
  traefik:
    image: traefik:v2.0
    ports:
      - "80:80"
      - "8081:8080"
    volumes:
      - ./configs/traefik.yaml:/traefik.yaml
  cop:
    image: tokend/traefik-cop:1.0.0
    restart: unless-stopped
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/cop.yaml:/config.yaml
    entrypoint: sh -c "traefik-cop run"
  upstream:
    image: nginx
    restart: unless-stopped
    volumes:
    - ./configs/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "8000:80"

  identities:
    image: registry.gitlab.com/tokend/nbu/identity-svc:75ed0f0cf5ba50870fb097ecd0f4f6cb49a1a0a9
    restart: unless-stopped
    entrypoint: sh -c "identity-svc migrate down && identity-svc run service"
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/identities.yaml:/config.yaml

  identities_db:
    image: tokend/postgres-ubuntu:9.6
    restart: unless-stopped
    environment:
      - POSTGRES_USER=identities
      - POSTGRES_PASSWORD=identities
      - POSTGRES_DB=identities
      - PGDATA=/pgdata
    volumes:
      - identities-data:/pgdata

  sallyport:
    image: registry.gitlab.com/tokend/nbu/sallyport-svc:b559a3764d83060f455dd9f5cbe52f1e761942fc
    environment:
      - KV_VIPER_FILE=/config.yaml
    command: run service
    volumes:
      - ./configs/sallyport.yaml:/config.yaml

volumes:
  identities-data:
