version: '3.3'

services:
  traefik:
    image: traefik:v2.0
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./configs/traefik.yaml:/traefik.yaml
  cop:
    image: registry.gitlab.com/tokend/traefik-cop:93dd46be8dccb36973bbfdfe4888b60d528df2ca # tokend/traefik-cop:1.0.0
    restart: unless-stopped
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/cop.yaml:/config.yaml
    entrypoint: sh -c "traefik-cop run"
  errors:
    image: tokend/error-handler-svc:0.0.1
    restart: unless-stopped
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/errors.yaml:/config.yaml
    entrypoint: sh -c "error-handler-svc run service"
  janus:
    image: tokend/janus:latest
    restart: unless-stopped
    volumes:
      - ./configs/janus.toml:/etc/janus/janus.toml
  upstream:
    image: nginx
    restart: unless-stopped
    volumes:
    - ./configs/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "8000:80"
    labels:
    - "traefik.frontend.passHostHeader=true"
  adks:
    image: tokend/adks:1.0.0
    restart: unless-stopped
    depends_on:
      - horizon
      - adks_db
    ports:
      - 8006:80
    volumes:
      - ./configs/adks.toml:/config.toml
  adks_db:
    image: tokend/postgres-ubuntu:9.6
    restart: unless-stopped
    environment:
      - POSTGRES_USER=adks
      - POSTGRES_PASSWORD=adks
      - POSTGRES_DB=adks
      - PGDATA=/pgdata
    volumes:
      - adks-data:/pgdata
  redis:
    image: redis:5.0-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
    command:
      - redis-server
      - --appendonly
      - "yes"
  core:
    image: tokend/core:3.6.3.1
    depends_on:
      - janus
    restart: unless-stopped
    environment:
      - POSTGRES_USER=core
      - POSTGRES_PASSWORD=core
      - POSTGRES_DB=core
      - PGDATA=/data/pgdata
      - ENSUREDB=1
      - CONFIG=/core-config.ini
    volumes:
      - ./configs/core.ini:/core-config.ini
      - core-data:/data
    labels:
      - "autoheal=true"
  horizon:
    image: tokend/horizon:3.7.1.1-rc.0
    depends_on:
      - core
    restart: unless-stopped
    environment:
      - POSTGRES_USER=horizon
      - POSTGRES_PASSWORD=horizon
      - POSTGRES_DB=horizon
      - PGDATA=/data/pgdata
    volumes:
      - ./configs/horizon.yaml:/config.yaml
      - horizon-data:/data
  api:
    image: tokend/identity:4.5.5-rc.0
    restart: unless-stopped
    depends_on:
      - horizon
      - api_db
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/api.yml:/config.yaml
    command: run
  api_db:
    image: tokend/postgres-ubuntu:9.6
    restart: unless-stopped
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=api
      - POSTGRES_DB=api
      - PGDATA=/pgdata
    volumes:
      - api-data:/pgdata
  initscripts:
    image: tokend/terraform-provider-tokend:1.3.0
    depends_on:
      - horizon
      - storage
    restart: on-failure
    volumes:
      - ./terraform:/opt/config
    entrypoint: ""
    command: /opt/config/apply.sh
  web_client:
    image: tokend/web-client:1.10.3
    restart: unless-stopped
    volumes:
      - ./configs/client.js:/usr/share/nginx/html/static/env.js
    ports:
      - 8060:80
  admin_client:
    image: tokend/admin-client:1.10.1
    restart: unless-stopped
    volumes:
      - ./configs/client.js:/usr/share/nginx/html/static/env.js
    ports:
      - 8070:80
  storage:
    image: minio/minio:RELEASE.2019-01-31T00-31-19Z
    restart: unless-stopped
    entrypoint: "sh"
    command: -c "mkdir -p /data/tfstate && minio server /data"
    environment:
      - MINIO_ACCESS_KEY=miniominio
      - MINIO_SECRET_KEY=sekritsekrit
      - MINIO_BROWSER=off
    volumes:
      - storage-data:/data

  ##
  ## Auxiliary modules
  ##

  # charts:
  #   image: tokend/charts:0.4.1
  #   restart: unless-stopped
  #   environment:
  #     - KV_VIPER_FILE=/config.yaml
  #   volumes:
  #     - ./configs/charts.yaml:/config.yaml
  #   ports:
  #     - 8080:8080
  #   command: run
  salecloser:
    image: tokend/sale-closer-svc:1.0.1
    depends_on:
      - horizon
    restart: unless-stopped
    volumes:
      - ./configs/salecloser.yaml:/config.yaml
    environment:
      - KV_VIPER_FILE=/config.yaml
    command: "run"
  poll_closer:
    image: tokend/poll-closer:0.1.1
    restart: unless-stopped
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/poll-closer.yaml:/config.yaml
    command: run closer

  ## 3rd party

  autoheal:
    image: willfarrell/autoheal
    restart: unless-stopped
    environment:
      - AUTOHEAL_START_PERIOD=60
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ##
  ## Integration services
  ##

  ## Coinpayments

  coinpayments-deposit:
    image: tokend/coinpayments:0.4.0
    restart: unless-stopped
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/coinpayments-deposit.yaml:/config.yaml
    command: deposit
  coinpayments-deposit-verify:
    image: tokend/coinpayments:0.4.0
    restart: unless-stopped
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/coinpayments-deposit-verify.yaml:/config.yaml
    command: deposit-verify
  coinpayments-withdraw:
    image: tokend/coinpayments:0.4.0
    restart: unless-stopped
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/coinpayments-withdraw.yaml:/config.yaml
    command: withdraw
  coinpayments-atomic-swap-checker:
    image: tokend/coinpayments:0.4.5
    restart: unless-stopped
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/coinpayments-atomic-swap-checker.yaml:/config.yaml
    command: atomic-swap-checker
  coinpayments-atomic-swap-matcher:
    image: tokend/coinpayments:0.4.5
    restart: unless-stopped
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/coinpayments-atomic-swap-matcher.yaml:/config.yaml
    command: atomic-swap-matcher
  rpayments-db-migrate:
    image: registry.gitlab.com/tokend/revolut/recurring-payments-svc:b3ddf1077f7c7ae521c84cac3f097cf36c3c08de
    restart: on-failure
    depends_on: 
      - recurring-payments-svc-db
    environment: 
      - KV_VIPER_FILE=/config.yaml
    volumes: 
      - ./configs/recpayments.yaml:/config.yaml
    command: migrate up 
  recurring-payments-svc:
    image: registry.gitlab.com/tokend/revolut/recurring-payments-svc:b3ddf1077f7c7ae521c84cac3f097cf36c3c08de
    restart: unless-stopped
    depends_on: 
      - horizon
      - recurring-payments-svc-db
      - rpayments-db-migrate
    environment: 
      - KV_VIPER_FILE=/config.yaml
    volumes: 
      - ./configs/recpayments.yaml:/config.yaml
    command: run service
  recurring-payments-svc-db:
    image: tokend/postgres-ubuntu:9.6
    restart: unless-stopped
    environment:
      - POSTGRES_USER=recpayments
      - POSTGRES_PASSWORD=recpayments
      - POSTGRES_DB=recpayments
      - PGDATA=/pgdata
    volumes:
      - recpayments-data:/pgdata

  ## Stellar
  stellar-deposit:
    image: tokend/stellar-deposit-svc:1.0.5
    restart: unless-stopped
    depends_on:
      - horizon
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/stellar-deposit.yaml:/config.yaml
  stellar-withdraw:
    image: tokend/stellar-withdraw-svc:1.0.1
    restart: unless-stopped
    depends_on:
      - horizon
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/stellar-withdraw.yaml:/config.yaml

  ## Ethereum
  erc20-deposit:
    image: tokend/erc20-deposit-svc:1.0.8
    restart: unless-stopped
    depends_on:
      - horizon
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/erc20-deposit.yaml:/config.yaml
    entrypoint: "erc20-deposit-svc"
    command: ["run", "deposit"]
  erc20-deployer:
    image: tokend/erc20-deposit-svc:1.0.8
    restart: on-failure
    depends_on:
      - horizon
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/erc20-deposit.yaml:/config.yaml
    entrypoint: "erc20-deposit-svc"
    command: ["run", "deployer"]
  erc20-funnel:
    image: tokend/erc20-deposit-svc:1.0.8
    restart: unless-stopped
    depends_on:
      - horizon
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/erc20-deposit.yaml:/config.yaml
    entrypoint: "erc20-deposit-svc"
    command: ["run", "funnel"]
  erc20-withdraw:
    image: tokend/erc20-withdraw-svc:1.0.5
    restart: unless-stopped
    depends_on:
      - horizon
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/erc20-withdraw.yaml:/config.yaml
    entrypoint: "erc20-withdraw-svc"
    command: ["run", "withdraw"]

volumes:
  adks-data:
  api-data:
  core-data:
  horizon-data:
  storage-data:
  redis-data:
  recpayments-data:
