log:
  disable_sentry: true

db:
  url: "postgres://ingester:ingester@ingester_db/ingester?sslmode=disable"

horizon:
  endpoint: "http://keys-horizon"
  signer: SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4

listener:
  addr: :80
