booking:
  skip_sign_check: false
  source: "GCFA67BVUVQWKXJQ2FHYBVNFXFFBRUPRQ4OAN6KT4GDMQSZVPPKGUJ7S"
  signer: "SADNAG6MK2JR6BI3CBSYHNSCLRSTZSEA4Y7PGJF6T5TBVJNKPDLF7PGS"
  scheduler: http://scheduler
  scheduler_signer: "SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4"

horizon:
  endpoint: http://janus
  signer: "SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4"

db:
  url: postgres://booking:booking@booking_db/booking?sslmode=disable

log:
  disable_sentry: true

listener:
  addr: :80

janus:
  endpoint: http://janus:8000
  upstream: http://booking
  surname:  booking