log:
  disable_sentry: true
  level: debug

keys:
  signer: "SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4"
  source: "GBA4EX43M25UPV4WIE6RRMQOFTWXZZRIPFAI5VPY6Z2ZVVXVWZ6NEOOB"

client:
  endpoint: http://traefik/

submit:
  endpoint: http://traefik/

settings:
  withdraw_to_destroy_tasks: "withdrawal_tasks:*"

cop:
  disabled: true