log:
  level: warn
  # we are using sentry for error collection,
  # you could opt-out by disabling it on the following line
  disable_sentry: false

sentry:
  dsn: https://591b6a3c375f4aa890a37532ce4969ec@sentry.tokend.services/4

horizon:
  endpoint: http://traefik
  signer: SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4

coinpayments:
  merchant_id: "ae907f7919abbd0eb5283e0b2172bcd6"
  address: https://www.coinpayments.net/api.php
  private_key: "319Eb4A46bDEB5a0dac600A8d60cfed6331eDcC58cCE2B3B39864b90fA06a7c4"
  public_key: "b510f391abc94f04bae6991ef89b7874c272c590c3d2d1067656c96de15009da"
  ipn_secret: "deprecated"
  request_timeout: 30

deposit_verify:
  source: GBA4EX43M25UPV4WIE6RRMQOFTWXZZRIPFAI5VPY6Z2ZVVXVWZ6NEOOB
  signer: SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4