log:
  disable_sentry: true

db:
  url: "postgres://dns:dns@dns_db/dns?sslmode=disable"

horizon:
  endpoint: "http://janus/"

listener:
  addr: :80

janus:
  disabled: false
  surname: dns
  endpoint: http://janus:8000
  upstream: http://dns

