log:
  disable_sentry: true

db:
  url: postgres://horizon:horizon@horizon_db/horizon?sslmode=disable

listener:
  addr: :80

core_db:
  url: postgres://core:core@core_db/core?sslmode=disable

core:
  url: http://core/core

horizon:
  ingest: true
  skip_sign_check: true

cop:
  endpoint: http://cop
  upstream: http://horizon
  service_name: "horizon-service"
  service_port: "80"
  service_prefix: "/horizon"