log:
  disable_sentry: true

db:
  url: postgres://horizon:horizon@horizon_db/horizon?sslmode=disable

listener:
  addr: :80

core_db:
  url: postgres://core:core@core_db/core?sslmode=disable

core:
  url: http://core:80/core

horizon:
  ingest: true
  skip_sign_check: false
  url: db_url

cop:
  disabled: true

  endpoint: http://cop
  upstream: http://horizon-service
  service_name: "horizon-service"
  service_port: "80"
  service_prefix: "/horizon"