log:
  disable_sentry: true

db:
  url: "postgres://identities:identities@identities_db/identities?sslmode=disable"

listener:
  addr: :80 # TODO configure and rm this TODO

cop:
  endpoint: "http://cop"
  upstream: "http://identities"
  service_name: "identities-svc"
  service_port: 80
  service_prefix: "/integrations/identities"

service:
  disable_encryption: false
  service_private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIICXAIBAAKBgQC350PIdcFex7ue9WlofdaEhRUjWPuJoGG96ZoKUR2nB5+b/AHa
    Hw/DezE7/T1mzfrfsuUyKtSVDvPfdYde9MxLO2Q6cMWi1vfvxImL0mbNSzFCKDpE
    MMpWGEZYcLEZKdkRbEuExjgPrugQ1bkFAsElYowH+FxB0ybDnoggraYrowIDAQAB
    AoGASaBfNNxgJJAWf5eFMf5fagLV6abwXbNGLoBd2Y+MLZkRv6NvImKZLwwdNAU5
    FfWVYQYAWMto/JxV6rrlDZE4UKCL2SjMbVXgCFbPk/PimCTve6738bgKi4OxjHH/
    kmfuZuNBE9gCErtIecRBjnSkQ6GPXDxfDs21C5yAAr38HFECQQDgLKJIJGJdcl0G
    pMkx25aPvJvvt3WU5ZSyVZSunGE04IyQP2HwOLhf0FnzZGZwe7w89Ko0y8TFGK3j
    LFvAEZ1nAkEA0gMHAncU29F/tSv6Tg3bjKVeceyBh7HAQ5sFLCM7md9+lFq++Uxp
    snbLWMkC96M/1o0ao7SYy7++fZnyfhceZQJBAIYIKb8Ygfd9OUGPpPu6XvrxugpJ
    lnPAEHfP02XS+guzdleIjfYi85nV6PItRVJbqOCJKHsImk19w/nfu7vKzGECQE4b
    8CR7k9d6IOyKUctsHgc+jlUC6N5GP0MlyhOzevxtApA8/CCOyhUlV9ZK1P6zyg+L
    ZagTiGzngPsIIgfBo30CQHCLZk3HUxKEI0gIAm0F4ZW457T4aWHzM74Oz/THvFR+
    9D5HDmyCmbNIp9SxdD1EbexsFngFJOQE91p2s0WC41A=
    -----END RSA PRIVATE recKEY-----

sdkconfig:
  # disabled: true
  config_file: /sdkconf.yaml
