log:
  disable_sentry: true

db:
  url: "postgres://identities:identities@identities_db:5432/identities?sslmode=disable"

listener:
  addr: :80 # TODO configure and rm this TODO

cop:
  endpoint: "http://cop"
  upstream: "http://identities"
  service_name: "identity-svc"
  service_port: 80
  service_prefix: "/integrations/identities"

service:
  ca_admin_identity_name: caadmin
  ca_admin_identity_password: caadminpw
  service_private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAvW+2VY8cGXWoLabXw4ZASf7sVeNiKoZjjpEA/z2NHMNAnEsi
    DvCUlwQtdYSKb5rT/24NCnyd6LZlAdv36DJGEJamNkD3k+5wEb0MxUeKIatL9gb5
    2WoSIqVlSc6GIQD6PaIDJATQDIz3t3LfOYaQDsZ0tkXL1kMlo1QnMrggSHHeyLo2
    a29/auTvk69GuaaZe4o4WCFWezK2v4O+DPdf3G7yq6hH0RHBXI8R8uThBno/mvAB
    8uAoufNMoaHHMWEybFhi0amzCxKvGHDKuQ32uXhmUsP13qmMH/WEzFfTcolVrFTL
    MJZqHjJslrIlYKUCUJJJhc7BWIckzCC87DLjGwIDAQABAoIBAGsysj2MdFw75mWf
    Cm4MpIi7B0Y7HCvwTJo6mBPX4uip3QAUzDskDRHAPXFJBYXOWbUrs5mBl2I/BL2e
    mpT9DgUJGxmMfg1qWmTPVFC3AQW4h427uNs9WPHeIok3o1M92F3UNm7Fgm33v55C
    FOvap96UkysqKAUhjkT0tBHRfANB44li69ZlrJ5KP7Q9DC/T8VEFaH9MF8EMmlMq
    jhttIkmKeTnL+T5tl6KeQ6nItQu6a9dUeWhvB53YKEuGFnerk6/QktHAWhiMcbVL
    AcVhElX5Cy97/VFxzkW5D9KFzU7YWtzje72s34Y26xXU8bWh6LnvtH+u72RQyLFa
    q/8nN0ECgYEA38rWM9NVvAxytP+zDu9Luy8X0GiiCINyhcsQpqbbcP9w/k7XFeGp
    mz++n27Pm1wjH4pbSxWdNcyJ9k0bIGoFDwm32bOM1ThgHZLhVwLWmpAeXyxkovMU
    7KV0dWuoefM86R6AJwPUNPmDCJsh2i286tGv2v5FHZukABIf3vI8Y3ECgYEA2LMa
    DRriyBrDslNlkRDxXugE1UWuuFVLyRT/WVlbm24yFGrrGeyZNs1gbPAm5XbEBykx
    w29g6DVFnuxKOUl6kg5sjXbVj5Rjcigo1x/TDKWio19B+yy/7v01L9L1LiSKt7Q1
    Tghj2c+OSglXceDquehUb8az7timQM53x847UUsCgYBITcqDGAadKRBudiat7pZz
    NbXl+chQI9f+bitFDKfdjEo/f81yHmSj6iZ2cGDW+x/F8ven/KW8WgdA8oyPHnHf
    9+3UgnQ/92TmaSww5pPbgDCv4zHoi8z44EQOI+hc7j+Buf8Bm/UV4H97alO3oAtn
    erPsdzZxaHXGKBTv/SeRoQKBgQCYdrrXiZkRrTMPHnoRbNhGK/xqiZJ6gxjFK47V
    MHexjgCSOP+cx8istCcpvnW/cKZPW351wMFv3ztSq3E1iStB5AAgMAHl+UNWqEbD
    xNJazZb2Vyk3La8E2QY41bZHdtJameH/Owv1zYCROq1ZpCPCFWKDGkyyuZ+PbTT9
    UW6OrQKBgCBJXrH1LCUSiVKjylS+Bf6417G5Euf6q4x/ZkGp80W3AT/5SaLcglrJ
    fRJ2pG95XshojBrhAhUJ1Ba1K4AaUze+diaUVvF30fkuZQRqiM0SoCrnVM4LAyU8
    022/rvY/Kx1tBkBHuDFa/n9P43TYFbSsZmT/2T/lCnYcvhxGJWuW
    -----END RSA PRIVATE KEY-----
