log:
  disable_sentry: true
  level: debug

db:
  url: postgres://identity:identity@identity_db?sslmode=disable

doorman:
  skip_sign_check: true

eth:
  disabled: false
  eth_identity_type: ethereum_pubkey

listener:
  addr: :80

client:
  endpoint: http://horizon

submit:
  endpoint: http://horizon

rbac:
  endpoint: http://....

service:
  skip_sign_check: true

cop:
  disabled: false
  endpoint: "http://cop"
  upstream: "http://identity-storage"
  service_name: "identity-storage"
  service_port: "80"
  service_prefix: "/integrations/identity-storage"
