log:
  disable_sentry: true
  level: debug

db:
  url: postgres://identity:identity@identity_storage_db/identity?sslmode=disable

listener:
  addr: :80

keys:
  signer: SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4
  source: GBA4EX43M25UPV4WIE6RRMQOFTWXZZRIPFAI5VPY6Z2ZVVXVWZ6NEOOB

client:
  endpoint: http://traefik

submit:
  endpoint: http://traefik

service:
  skip_sign_check: true

cop:
  endpoint: http://cop
  upstream: http://identity_storage
  service_name: "identity-storage-service"
  service_port: "80"
