log:
  disable_sentry: true
  level: debug

db:
  url: postgres://identity_storage:identity_storage@identity_storage_db/identity_storage?sslmode=disable

listener:
  addr: :80

service:
  skip_sign_check: true

client:
  endpoint: http://traefik/

submit:
  endpoint: http://traefik/

rbac:
  endpoint: http://traefik/
  skip_check: true

keys:
  source: GBA4EX43M25UPV4WIE6RRMQOFTWXZZRIPFAI5VPY6Z2ZVVXVWZ6NEOOB
  signer: SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4

cleaner:
  verification_term: 1h

cop:
  endpoint: http://cop
  upstream: http://identity-storage
  service_name: identity-storage
  service_port: "80"
  #service_prefix: