log:
  disable_sentry: true
  level: debug

listener:
  addr: :80

mercado:
  endpoint: https://api.mercadopago.com
  access_token: TEST-7492097937676279-030415-1a413db235ddae22e5771b33737d17e8-522013668
  notification_domain: http://17d9465d.ngrok.io/_/api/
  success_url: http://localhost:8061/dashboard
  pending_url: http://localhost:8061
  failure_url: http://localhost:8061
  sandbox_mode: true

client:
  endpoint: http://traefik/

submit:
  endpoint: http://traefik/

keys:
  source: GBA4EX43M25UPV4WIE6RRMQOFTWXZZRIPFAI5VPY6Z2ZVVXVWZ6NEOOB
  signer: SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4

cop:
  endpoint: "http://cop"
  upstream: "http://mercado"
  service_name: "mercado-service"
  service_port: "80"
  service_prefix: "/integrations/mercado"

