config:
  stellar_core_url:                        http://pkicore:8080
  stellar_core_database_url:               postgres://pkicore:pkicore@pkicore/pkicore?sslmode=disable
  hostname:                                ""
  database_url:                            postgres://pkihorizon:pkihorizon@localhost/pkihorizon?sslmode=disable
  log_level:                               "warn"
  slow_query_bound:                        1s
  port:                                    80
  ingest:                                  true
  stale_threshold:                         0
  sign_checkskip:                          false
  cors_enabled:                            false
  disable_api_submit:                      true
  disable_tx_tfa:                          true
  force_https_links:                       false
  # we are using sentry for error collection, you could opt-out by removing following line
  sentry_dsn:                              "https://0ad42a3fc393412a94b8e09d342aaed1@sentry.tokend.services/7"
  sentry_log_level:                        "warn"
  project:                                 "pkihorizon"
  env:                                     "developer-edition"
  migrate_up_on_start:                     true
  api_backend:                             http://black.hole
  template_backend:                        http://templatesprovider
  invest_ready:                            http://black.hole
  telegram_airdrop:                        http://black.hole

janus:
  endpoint: http://janus:8000
  upstream: http://pkihorizon
  surname: pkihorizon
