s3:
  region: us-east-1
  use_static_credentials: false

template_provider:
  bucket: "tokend-default-templates"

listener:
  addr: :80
                
log:
  level: info
  disable_sentry: true

janus:
  endpoint: http://janus:8000
  surname: templatesprovider
  upstream: http://templatesprovider

